### PR TITLE
Update the authorize lib version to bring in updated depdencies with security fixes

### PR DESCRIPTION
**Pull request by dkjellin**
This feels generally safe, but I have no good insight into what tests need to be performed.

### CODE REVIEW

**Review by justinskariah — APPROVED** [review]
Looks good, I would do the following tests
* Build the plugin and ensure the bundled library is updated
* Deploy BBS on Azure and verify that the nodes discover each other. This plugin's job is to ensure hazelcast  nodes can discovery each other in Azure

**Comment by dkjellin** [comment]
> Looks good, I would do the following tests
> 
>     * Build the plugin and ensure the bundled library is updated
> 
>     * Deploy BBS on Azure and verify that the nodes discover each other. This plugin's job is to ensure hazelcast  nodes can discovery each other in Azure

Excellent, I'll do that. 
I have already built the plugin, so I know that bit works. I'll spin up a cluster and see if it works, I assume it does but I'll try it.
Thank you

**Comment by bturner** [comment]
This is now in our fork, which is fine, but where are we at on un-forking? We've gotten off the fork for the primary Hazelcast repository. Have we opened any pull request to try and contribute this change, or any other changes that tie us to our fork, back to the canonical repository?

**Comment by dkjellin** [comment]
@justinskariah maybe you can answer Bryan's questions?
I don't know if the fork is still needed, nor if a PR was attempted.

**Pull request merged**
